# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/meta-schema.json
name: "MERGE_IDS"
description: merge ids subworkflow for the reportho pipeline
keywords:
  - reportho
  - merge
  - ids
components:
  - DIAMOND_CLUSTER
  - GROUP_DIAMOND
  - MERGE_ALL
  - MERGE_DIAMOND
  - MERGE_FASTA_IDS
  - POSTPROCESS_DIAMOND
  - REDUCE_IDMAP
  - SPLIT_TAXIDS
input:
  - ch_fasta_all:
      type: channel
      description: "Input channel 'ch_fasta_all'"
output:
  - id_clusters:
      type: channel
      description: "Output channel 'id_clusters' emitted from expression: ch_id_clusters"
  - id_map:
      type: channel
      description: "Output channel 'id_map' emitted from expression: ch_id_map"
  - versions:
      type: channel
      description: "Output channel 'versions' emitted from expression: ch_versions"
authors:
  - "@itrujnara"
maintainers:
  - "@itrujnara"
