lint:
  files_exist:
    - conf/igenomes.config
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - docs/images/nf-core-reportho_logo_light.png
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
nf_core_version: 3.4.1
repository_type: pipeline
template:
  author: itrujnara
  description: A pipeline for ortholog fetching and analysis
  force: false
  is_nfcore: true
  name: reportho
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - igenomes
  version: 1.1.0
