# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "SPLIT_ID_FORMAT"
description: split id format for the reportho pipeline
keywords:
  - reportho
  - split
  - id
  - format
tools: []
input:
  - ids:
      type: tuple
      description: "Nextflow input declaration: tuple val(meta), path(ids)"
output:
  - ids_split:
      type: tuple
      description: "Nextflow output declaration: tuple val(meta), path('*_ids.txt'), emit: ids_split"
  - versions:
      - versions.yml:
          type: file
          description: 'Output file emitted by this process: path "versions.yml"               , emit: versions'
          pattern: "versions.yml"
authors:
  - "@itrujnara"
maintainers:
  - "@itrujnara"
