# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "GET_SEQUENCES"
description: get sequences subworkflow for the reportho pipeline
keywords:
  - reportho
  - get
  - sequences
components:
  - CONCAT_FASTA
  - CONCAT_HITS
  - CONCAT_MISSES
  - FETCH_ENSEMBL_IDMAP
  - FETCH_ENSEMBL_SEQUENCES
  - FETCH_OMA_SEQUENCES
  - FETCH_REFSEQ_SEQUENCES
  - FETCH_UNIPROT_SEQUENCES
  - SPLIT_ID_FORMAT
input:
  - ch_ids:
      type: channel
      description: "Input channel 'ch_ids'"
  - ch_query_fasta:
      type: channel
      description: "Input channel 'ch_query_fasta'"
output:
  - fasta:
      type: channel
      description: "Output channel 'fasta' emitted from expression: CONCAT_FASTA.out.file_out"
  - hits:
      type: channel
      description: "Output channel 'hits' emitted from expression: CONCAT_HITS.out.file_out"
  - misses:
      type: channel
      description: "Output channel 'misses' emitted from expression: CONCAT_MISSES.out.file_out"
  - versions:
      type: channel
      description: "Output channel 'versions' emitted from expression: ch_versions"
authors:
  - "@itrujnara"
maintainers:
  - "@itrujnara"
