# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: fetch_ensembl_idmap
description: Download and build an Ensembl to UniProt identifier mapping table
keywords:
  - ensembl
  - idmap
  - uniprot
  - mapping
tools:
  - python:
      description: Python is a programming language that lets you work quickly and integrate systems more effectively.
      homepage: https://www.python.org/
      documentation: https://docs.python.org/3/
      licence: ["PSF-2.0"]
  - requests:
      description: Requests is a simple, yet elegant, HTTP library.
      homepage: https://requests.readthedocs.io/
      documentation: https://requests.readthedocs.io/
      licence: ["Apache-2.0"]
output:
  idmap:
    - - ensembl_idmap.csv:
          type: file
          description: CSV file containing Ensembl to UniProt identifier mappings
          pattern: "ensembl_idmap.csv"
  versions_python:
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python --version | sed 's/Python //':
          type: eval
          description: The expression to obtain the version of the tool
  versions_requests:
    - - ${task.process}:
          type: string
          description: The name of the process
      - requests:
          type: string
          description: The name of the tool
      - "pip show requests | sed -n 's/^Version: //p'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python --version | sed 's/Python //':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - requests:
          type: string
          description: The name of the tool
      - "pip show requests | sed -n 's/^Version: //p'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@itrujnara"
maintainers:
  - "@itrujnara"
