# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "PLOT_ORTHOLOGS"
description: plot orthologs for the reportho pipeline
keywords:
  - reportho
  - plot
  - orthologs
tools: []
input:
  - score_table:
      type: tuple
      description: "Nextflow input declaration: tuple val(meta), path(score_table)"
output:
  - supports:
      - meta:
          type: map
          description: "Groovy map with sample metadata propagated from input"
      - "*_supports_dark.png":
          type: file
          description: "Output file emitted by this process: tuple val(meta), path(\"*_supports_light.png\"), path(\"*_supports_dark.png\"), emit: supports"
          pattern: "*_supports_dark.png"
  - venn:
      - meta:
          type: map
          description: "Groovy map with sample metadata propagated from input"
      - "*_venn_dark.png":
          type: file
          description: "Output file emitted by this process: tuple val(meta), path(\"*_venn_light.png\"), path(\"*_venn_dark.png\")        , emit: venn"
          pattern: "*_venn_dark.png"
  - jaccard:
      - meta:
          type: map
          description: "Groovy map with sample metadata propagated from input"
      - "*_jaccard_dark.png":
          type: file
          description: "Output file emitted by this process: tuple val(meta), path(\"*_jaccard_light.png\"), path(\"*_jaccard_dark.png\")  , emit: jaccard"
          pattern: "*_jaccard_dark.png"
  - versions:
      - versions.yml:
          type: file
          description: "Output file emitted by this process: path \"versions.yml\"                                                       , emit: versions"
          pattern: "versions.yml"
authors:
  - "@itrujnara"
maintainers:
  - "@itrujnara"
