# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: fetch_panther_group_local
description: Retrieve PANTHER ortholog group members from a local PANTHER data file
keywords:
  - panther
  - orthology
  - uniprot
  - local-database
tools:
  - python:
      description: Python is a programming language that lets you work quickly and integrate systems more effectively.
      homepage: https://www.python.org/
      documentation: https://docs.python.org/3/
      licence: ["PSF-2.0"]
  - ripgrep:
      description: ripgrep recursively searches directories for a regex pattern while respecting your gitignore rules.
      homepage: https://github.com/BurntSushi/ripgrep
      documentation: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md
      licence: ["MIT", "Unlicense"]
input:
  - - meta:
        type: map
        description: Groovy Map containing sample metadata
    - uniprot_id:
        type: file
        description: File containing the UniProt identifier used as query
    - taxid:
        type: file
        description: File containing taxonomy identifier associated with the query
    - exact:
        type: file
        description: File indicating whether the ID was found through exact match
  - panther_db:
      type: file
      description: Local PANTHER data file used to recover ortholog group members
      pattern: "*"
output:
  panther_group:
    - - meta:
          type: map
          description: Groovy Map containing sample metadata
      - "*_panther_group.csv":
          type: file
          description: CSV file listing recovered PANTHER ortholog group members
          pattern: "*_panther_group.csv"
  versions:
    - - versions.yml:
          type: file
          description: File containing software versions used in the module
          pattern: "versions.yml"
authors:
  - "@itrujnara"
maintainers:
  - "@itrujnara"
