# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: fetch_oma_group_online
description: Fetch OMA ortholog group members from the online OMA API
keywords:
  - oma
  - orthology
  - uniprot
  - api
tools:
  - python:
      description: Python is a programming language that lets you work quickly and integrate systems more effectively.
      homepage: https://www.python.org/
      documentation: https://docs.python.org/3/
      licence: ["PSF-2.0"]
  - biopython:
      description: Biopython is a set of freely available tools for biological computation.
      homepage: https://biopython.org/
      documentation: https://biopython.org/wiki/Documentation
      doi: 10.1093/bioinformatics/btp163
      licence: ["Biopython"]
  - requests:
      description: Requests is a simple, yet elegant, HTTP library.
      homepage: https://requests.readthedocs.io/
      documentation: https://requests.readthedocs.io/
      licence: ["Apache-2.0"]
input:
  - - meta:
        type: map
        description: Groovy Map containing sample metadata
    - uniprot_id:
        type: file
        description: File containing the UniProt identifier used as query
    - taxid:
        type: file
        description: File containing taxonomy identifier associated with the query
    - exact:
        type: file
        description: File indicating whether the ID was found through exact match
output:
  oma_group:
    - - meta:
          type: map
          description: Groovy Map containing sample metadata
      - "*_oma_group.csv":
          type: file
          description: CSV file listing retrieved OMA ortholog group members
          pattern: "*_oma_group.csv"
  versions:
    - - versions.yml:
          type: file
          description: File containing software versions used in the module
          pattern: "versions.yml"
authors:
  - "@itrujnara"
maintainers:
  - "@itrujnara"
