# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "IDENTIFY_SEQ_ONLINE"
description: identify seq online for the reportho pipeline
keywords:
  - reportho
  - identify
  - seq
  - online
tools: []
input:
  - fasta:
      type: tuple
      description: "Nextflow input declaration: tuple val(meta), path(fasta)"
output:
  - seqinfo:
      - meta:
          type: map
          description: "Groovy map with sample metadata propagated from input"
      - "*_exact.txt":
          type: file
          description: 'Output file emitted by this process: tuple val(meta), path("*_id.txt"), path("*_taxid.txt"), path("*_exact.txt"), emit: seqinfo'
          pattern: "*_exact.txt"
  - versions:
      - versions.yml:
          type: file
          description: 'Output file emitted by this process: path "versions.yml"                                                        , emit: versions'
          pattern: "versions.yml"
authors:
  - "@itrujnara"
maintainers:
  - "@itrujnara"
