# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "FETCH_EGGNOG_GROUP_LOCAL"
description: fetch eggnog group local for the reportho pipeline
keywords:
  - reportho
  - fetch
  - eggnog
  - group
  - local
tools: []
input:
  - uniprot_id:
      type: tuple
      description: "Nextflow input declaration: tuple val(meta), path(uniprot_id), path(taxid), path(exact)"
  - db:
      type: file
      description: "Nextflow input declaration: path db"
      pattern: "*"
  - eggnog_idmap:
      type: file
      description: "Nextflow input declaration: path eggnog_idmap"
      pattern: "*"
  - ensembl_idmap:
      type: file
      description: "Nextflow input declaration: path ensembl_idmap"
      pattern: "*"
  - refseq_idmap:
      type: file
      description: "Nextflow input declaration: path refseq_idmap"
      pattern: "*"
output:
  - eggnog_group:
      - meta:
          type: map
          description: "Groovy map with sample metadata propagated from input"
      - "*_eggnog_group.csv":
          type: file
          description: 'Output file emitted by this process: tuple val(meta), path("*_eggnog_group.csv"), emit: eggnog_group'
          pattern: "*_eggnog_group.csv"
  - versions:
      - versions.yml:
          type: file
          description: 'Output file emitted by this process: path "versions.yml"                        , emit: versions'
          pattern: "versions.yml"
authors:
  - "@itrujnara"
maintainers:
  - "@itrujnara"
